clear; clc; close all;
load('data_1.mat')
figure()
plot(r_1.time,r_1.signals.values)
xlabel('time')
ylabel('amplitude')
figure()
plot(u_1.time,u_1.signals.values)
xlabel('time')
ylabel('amplitude')
figure()
plot(y_1.time,y_1.signals.values)
xlabel('time')
ylabel('arm degree[^o]')
ylim([-360 360])